# Generated by Django 4.1.4 on 2022-12-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('usn', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=12)),
                ('phone', models.CharField(max_length=10)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
